### ISSUE TITLE
Coq Utils fails to build with Coq 8.10.2

### ISSUE THREAD

**Issue by robblanco** [arthuraa/coq-utils#4]
The current master fails to build with Coq 8.10.2 (with OCaml 4.08.0). OPAM package versions are as prescribed in the README, The source hash for the development version of `coq-deriving` is db78af07.

In particular, the following two definitions in `nominal.v` are problematic. If they are commented out, the build succeeds.

```
Canonical string_nominalType := Eval hnf in [nominalType for string by //].
Canonical string_trivialNominalType :=
  Eval hnf in [trivialNominalType for string].
```

The error message:

```
File "./theories/nominal.v", line 680, characters 44-74:
Error:
In environment
x : phantom (Ord.class_of ?cT) (Ord.class ?cT)
The term "x" has type "phantom (Ord.class_of ?cT) (Ord.class ?cT)"
while it is expected to have type "phantom (Ord.class_of string) ?c".
```

**Comment by arthuraa** [comment]
Sorry about this. The issue was that the library was relying on functionality of the development version of `extructures`. If you install that version, the problem should go away.
