### ISSUE TITLE
Removing dependency on coq-void

### ISSUE THREAD

**Issue by robblanco** [arthuraa/coq-utils#5]
Since `coq-void`'s functionality has been integrated in Mathematical Components, it would be good to remove that dependency and bump the required version of MathComp. I have found no disadvantages to doing so with Coq versions 8.10 through 8.12.

**Comment by arthuraa** [comment]
Thanks a lot for pointing this out! These last weeks have been a bit crazy, but I'll hopefully get to this soon. PRs are always welcome too, of course. ;)

**Comment by arthuraa** [comment]
I just updated the requirements.
