### ISSUE TITLE
Nominal.sort type error.

### ISSUE THREAD

**Issue by selenelinares** [arthuraa/coq-utils#6]
Hi, 

The current master fails to build with the following versions:
`coq: 8.11.2   
coq-mathcomp-algebra: 1.11.0  
coq-mathcomp-fingroup: 1.11.0  
coq-mathcomp-ssreflect: 1.11.0  
coq-extructures and coq-deriving: dev version `

The error message:
`File "./theories/nominal.v", line 78, characters 38-47:
Error:
In environment
D : {fset name}
A : {fset name}
The term "avoid D A" has type "{fperm name}"
while it is expected to have type "?T0 -> ?S".
`
Could you help me, please?

**Comment by arthuraa** [comment]
Hi,

Thanks for reporting this, and sorry for the delay in getting back to you! I'll have a look at the error.

If you don't mind, why are you interested in this library?

**Comment by arthuraa** [comment]
@selenelinares The code seems to compile now under 8.11.0 with the development versions of the libraries of `extructures` and `deriving`. Would you mind checking if you can get it to compile? (I haven't tested the code for deriving nominal instances, though...)

I've been meaning to cleanup the nominal library to make it more usable for others, but haven't had the time to do so. It is also lacking a lot of features that you might expect (e.g. name abstraction). If you were planning on using it for anything more interesting, I would love to hear about it, though!

**Comment by selenelinares** [comment]
@arthuraa It compiles now, thank you. 

I've just started my PhD. I've been exploring memory safety characterizations, found your work The Meaning of Memory Safety and that's why I'm here. Not sure to what extent I'll be working on this line, but if something interesting comes up, sure I'll let you know.

Thank you again.
